# Generated by Django 4.2 on 2023-05-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='sets',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workouts',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
