# Generated by Django 4.2 on 2023-05-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_remove_workouts_created_remove_workouts_exercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
