# Generated by Django 4.2.1 on 2023-05-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_exercise_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='created',
        ),
    ]
