# Generated by Django 4.2.1 on 2023-05-14 11:06

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_remove_exercise_created_workouts_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
        ),
    ]
