# Generated by Django 4.2.1 on 2023-05-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_workouts_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
