# Generated by Django 4.2.1 on 2023-05-14 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0007_alter_workouts_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
